image: ruby:2.7.1

cache:
  paths:
    - vendor/

before_script:
  - bundle install --path vendor

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public/
  artifacts:
    paths:
      - public
  only:
    - master
